// Flat config for ESLint 9, so `npx eslint .` works the same as `next lint`.
//
// `.eslintrc.json` (`{ extends: ["next/core-web-vitals", "next/typescript"] }`)
// is what `next lint` itself resolves — Next 15.5's lint runner still speaks
// the legacy config format internally and does not read this file. ESLint 9's
// own CLI, on the other hand, only speaks flat config and ignores
// `.eslintrc.json` entirely. Rather than maintain two rule sets, `FlatCompat`
// loads the exact same shareable configs `next/core-web-vitals` and
// `next/typescript` already point at and translates them into flat form, so
// both commands enforce one set of rules from one pair of names.
import { FlatCompat } from '@eslint/eslintrc';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const compat = new FlatCompat({
  baseDirectory: path.dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    // Flat config has no implicit ignore list of its own; `next lint` gets
    // this for free from `.next`'s presence and its own knowledge of
    // Next-generated files, ESLint 9's CLI does not. `next-env.d.ts` is
    // regenerated by Next on every build and is gitignored — it is not ours
    // to lint, and its triple-slash reference is Next's own convention.
    ignores: ['.next/**', '.next-prod/**', 'node_modules/**', 'public/**', 'next-env.d.ts'],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default config;
